# Gamestyles sorted from easiest to hardest/most controversial
def get_questionset(style: str):
    global questionsets
    if style in questionsets.keys():
        return questionsets[style]
    else:
        return None
    
def get_styles():
    global questionsets
    return list(questionsets.keys())

controversial_fi = [
    {"question": "Kuka todennäköisimmin menisi naimisiin rahasta?"},
    {"question": "Kumpi on paremman näköinen?"},
    {"question": "Kuka äänestää Trumpia?"},
    {"question": "Kuka fanittaa Andrew Tatea?"},
    {"question": "Kumman kanssa menisit mieluummin sänkyyn?"},
    {"question": "Kumpi on enemmän alfa?"},
    {"question": "Kumpi on enemmän simp?"},
    {"question": "Kuka todennäköisimmin unohtaa ystävänsä syntymäpäivän?"},
    {"question": "Kuka todennäköisimmin unohtaa avaimensa kotiin?"},
    {"question": "Kumpi on juonut enemmän?"},
    {"question": "Kumpi googlaa itseään (enemmän)?"},
    {"question": "Kuka todennäköisimmin myy sielunsa paholaiselle?"},
    {"question": "Kuka todennäköisimmin esiintyy alastonkuvissa?"},
    {"question": "Kuka todennäköisimmin varastaa ystävänsä kumppanin?"},
    {"question": "Kuka todennäköisimmin jää kiinni pettämisestä?"},
    {"question": "Kuka todennäköisimmin joutuu vankilaan?"},
    {"question": "Kuka todennäköisimmin valehtelee ikänsä?"},
    {"question": "Kuka todennäköisimmin käyttää huumeita?"},
    {"question": "Kuka todennäköisimmin osallistuu orgioihin?"},
    {"question": "Kuka todennäköisimmin tekee muovileikkauksia?"},
    {"question": "Kuka todennäköisimmin jättää laskut maksamatta?"},
    {"question": "Kuka todennäköisimmin ajaa humalassa?"},
    {"question": "Kuka todennäköisimmin menettää työnsä skandaalin takia?"},
    {"question": "Kuka todennäköisimmin valehtelee CV:ssä?"},
    {"question": "Kuka todennäköisimmin käyttää treffisovelluksia salaa?"},
    {"question": "Kuka todennäköisimmin osallistuu mielenosoituksiin?"},
    {"question": "Kuka todennäköisimmin jättää perheensä?"},
    {"question": "Kuka todennäköisimmin tekee rikosilmoituksen väärin perustein?"},
    {"question": "Kuka todennäköisimmin käyttää väärin yrityksen varoja?"},
    {"question": "Kuka todennäköisimmin osallistuu laittomiin vedonlyönteihin?"},
    {"question": "Kuka todennäköisimmin käyttää väärin lääkkeitä?"},
    {"question": "Kuka todennäköisimmin käyttää väärin sosiaalietuuksia?"},
    {"question": "Kuka todennäköisimmin osallistuu laittomiin maahanmuuttojärjestelyihin?"},
    {"question": "Kuka todennäköisimmin osallistuu laittomiin aseiden kauppoihin?"},
    {"question": "Kumman seksuaalisuus on enemmän kyseenalaista?"},
    {"question": "Kuka todennäköisimmin joutuu laivan putkaan?"},
    {"question": "Kumpi ottaa shotin?"},
    {"question": "Kumpi juo juomansa loppuun?"},
    {"question": "Kumpi puhuu englantia seuraavat 10 min?"},
    {"question": "Kumpi puhuu ruotsia seuraavat 10 min?"},
    {"question": "Kumpi masturboi joka päivä?"},
    {"question": "Kumpi masturboi kun pääsee kotiin?"},
    {"question": "Kuka todennäköisemmin selviäisi nälkäpelistä ryhmän jäseniä vastaan?"},
    {"question": "Kuka todennäköisimmin tekee veropetoksen?"},
    {"question": "Kumpi voittaisi kaksintaistelun toista henkilöä vastaan?"},
    {"question": "Kuka todennäköisimmin rupeaa poliitikoksi?"},
    {"question": "Kumpi todennäköisimmin rupeaa nunnaksi/munkiksi?"},
    {"question": "Kuka todennäköisimmin rupeaa pornotähdeksi?"},
    {"question": "Kuka todennäköisimmin rupeaa alkoholistiksi?"},
    {"question": "Kuka todennäköisimmin rupeaa uskonnolliseksi johtajaksi?"},
    {"question": "Kummalla on paremmat tanssiliikkeet?"},
    {"question": "Kummalla on parempi keskiarvo?"},
    {"question": "Kumpi harrastaa enemmän seksiä?"},
    {"question": "Kuka todennäköisimmin ei kannata aborttia?"},
    {"question": "Kumpi on seksikkäämpi?"},
    {"question": "Kummalla on ollut enemmän seksikumppaneita?"},
    {"question": "Kuka todennäköisimmin etsii seksikumppaneita tänään?"},
    {"question": "Kumpi näyttää internetin selaushistoriansa?"},
    {"question": "Kuka todennäköisimmin flirttailee baaritiskillä saadakseen ilmaisen juoman?"},
    {"question": "Kumpi voisi mennä sokkotreffeille ilman tietoa parin sukupuolesta?"},
    {"question": "Kuka todennäköisimmin kokee, ettei yksi kumppani riitä?"},
    {"question": "Kuka todennäköisimmin eksyy matkalla lähikauppaan?"},
    {"question": "Kumpi voittaa beerpongissa?"},
    {"question": "Kuka todennäköisimmin unohtaa että missä asuu?"},
    {"question": "Kuka todennäköisimmin elää kaksoiselämää?"}
]

controversial_en = [
    {"question": "Who is most likely to hit the jackpot at a Casino?"},
    {"question": "Who is most likely to marry for money?"},
    {"question": "Who looks better?"},
    {"question": "Who would you rather go to bed with?"},
    {"question": "Who is more alpha?"},
    {"question": "Who is more of a simp?"},
    {"question": "Who is most likely to forget their friend's birthday?"},
    {"question": "Who is most likely to forget their keys at home?"},
    {"question": "Who has drunk more?"},
    {"question": "Who votes for Trump?"},
    {"question": "Who is a fan of Andrew Tate?"},
    {"question": "Who googles themselves (more)?"},
    {"question": "Who is most likely to sell their soul to the devil?"},
    {"question": "Who is most likely to appear in nude photos?"},
    {"question": "Who is most likely to steal their friend's partner?"},
    {"question": "Who is most likely to get caught cheating?"},
    {"question": "Who is most likely to end up in jail?"},
    {"question": "Who is most likely to lie about their age?"},
    {"question": "Who is most likely to use drugs?"},
    {"question": "Who is most likely to participate in orgies?"},
    {"question": "Who is most likely to get plastic surgery?"},
    {"question": "Who is most likely to leave bills unpaid?"},
    {"question": "Who is most likely to drive drunk?"},
    {"question": "Who is most likely to lose their job due to a scandal?"},
    {"question": "Who is most likely to lie on their CV?"},
    {"question": "Who is most likely to use dating apps secretly?"},
    {"question": "Who is most likely to participate in protests?"},
    {"question": "Who is most likely to abandon their family?"},
    {"question": "Who is most likely to file a false police report?"},
    {"question": "Who is most likely to misuse company funds?"},
    {"question": "Who is most likely to participate in illegal betting?"},
    {"question": "Who is most likely to misuse medication?"},
    {"question": "Who is most likely to abuse social benefits?"},
    {"question": "Who is most likely to participate in illegal immigration arrangements?"},
    {"question": "Who is most likely to participate in illegal arms trade?"},
    {"question": "Whose sexuality is more questionable?"},
    {"question": "Who is most likely to end up in the ship's jail?"},
    {"question": "Who takes a shot?"},
    {"question": "Who finishes their drink?"},
    {"question": "Who speaks Swedish for the next 10 min?"},
    {"question": "Who would most likely survive the Hunger Games against group members?"},
    {"question": "Who is most likely to commit tax fraud?"},
    {"question": "Who would win in a duel against the other person?"},
    {"question": "Who is most likely to become a politician?"},
    {"question": "Who is most likely to become a nun/monk?"},
    {"question": "Who is most likely to become a porn star?"},
    {"question": "Who is most likely to become an alcoholic?"},
    {"question": "Who is most likely to become a religious leader?"},
    {"question": "Who has better dance moves?"},
    {"question": "Who is smarter?"},
    {"question": "Who masturbates every day?"},
    {"question": "Who will masturbate after they get home tonight?"},
    {"question": "Who has more sex?"},
    {"question": "Who is most likely to oppose abortion?"},
    {"question": "Who is sexier?"},
    {"question": "Who has had more sexual partners?"},
    {"question": "Who is most likely to look for sexual partners tonight?"},
    {"question": "Who shows their internet browsing history?"},
    {"question": "Who is most likely to flirt at the bar for free drinks?"},
    {"question": "Who could go on a blind date without knowing the partner's gender?"},
    {"question": "Who is most likely to feel one partner isn't enough?"},
    {"question": "Who is most likely to get lost on the way to the local store?"},
    {"question": "Who wins at beer pong?"},
    {"question": "Who would you rather have as your only friend for life?"},
    {"question": "Who is most likely to try switching cabins with another passenger at night?"},
    {"question": "Who is most likely to live a double life?"}
]

easy_en = [
    {"question": "Who woke up earlier today?"},
    {"question": "Who spends more time on social media?"},
    {"question": "Who eats healthier?"},
    {"question": "Who loves animals more?"},
    {"question": "Who is a better cook?"},
    {"question": "Who is more likely to be late to meetings?"},
    {"question": "Who has a better memory?"},
    {"question": "Who is more organized?"},
    {"question": "Who would make a better teacher?"},
    {"question": "Who is more likely to help strangers?"},
    {"question": "Who has better taste in music?"},
    {"question": "Who is more likely to cry during movies?"},
    {"question": "Who would survive longer without their phone?"},
    {"question": "Who is better at keeping plants alive?"},
    {"question": "Who is more likely to forget birthdays?"},
    {"question": "Who would make a better nurse?"},
    {"question": "Who is more patient?"},
    {"question": "Who has better stories to tell?"},
    {"question": "Who would be a better tour guide?"},
    {"question": "Who would be a better stand-up comedian?"},
    {"question": "Who would win in a karaoke contest?"},
    {"question": "Who would win a trivia contest?"},
    {"question": "Who would do better on a reality TV show?"},
    {"question": "Who is more likely to start a new hobby?"}
]

medium_en = [
    {"question": "Who is more likely to become a millionaire?"},
    {"question": "Who would win in a karaoke contest?"},
    {"question": "Who would make a better detective?"},
    {"question": "Who would adapt better to living in another country?"},
    {"question": "Who is more likely to start their own business?"},
    {"question": "Who would win in a chess match?"},
    {"question": "Who would get more followers as a social media influencer?"},
    {"question": "Who would write a better novel?"},
    {"question": "Who would be a better radio host?"},
    {"question": "Who would win in a debate competition?"},
    {"question": "Who is better at negotiating?"},
    {"question": "Who would make a better actor/actress?"},
    {"question": "Who would win a talent show?"},
    {"question": "Who would be better at learning a new language?"},
    {"question": "Who would make a better team captain?"},
    {"question": "Who would be more successful in sales?"},
    {"question": "Who would do better on a reality TV show?"},
    {"question": "Who would be a better public speaker?"},
    {"question": "Which one finishes their drink?"},
    {"question": "Who has the best pickup lines?"},
    {"question": "Who would make more money as a street performer?"},
    {"question": "Who is more likely to become Instagram famous?"},
    {"question": "Who would survive longer without coffee?"},
    {"question": "Who has better fashion sense?"},
    {"question": "Who would win in a dance battle?"},
    {"question": "Who is most likely to become a viral meme?"},
    {"question": "Who would make a better bartender?"},
    {"question": "Who has the worst taste in music?"},
    {"question": "Who would win in an arm wrestling match?"},
    {"question": "Who is more likely to become a famous DJ?"},
    {"question": "Who would make a better food critic?"},
    {"question": "Who has the most embarrassing childhood story?"},
    {"question": "Who would be better at giving relationship advice?"},
    {"question": "Who is more likely to end up on a billboard?"},
    {"question": "Who would make a better game show host?"},
    {"question": "Who would win in a cooking competition?"},
    {"question": "Who is more likely to become a social media trend?"},
    {"question": "Who would make a better personal trainer?"},
    {"question": "Who has the better party playlist?"},
    {"question": "Takes a sip from their drink!"},
    {"question": "Who does 10 pushups?"}
]

hard_en = [
    {"question": "Who would survive longer on a desert island?"},
    {"question": "Who would win in a boxing match?"},
    {"question": "Who has a double life?"},
    {"question": "Who would make a better president?"},
    {"question": "Who saves the world in a zombie apocalypse?"},
    {"question": "Who makes their first million first?"},
    {"question": "Who would you trust with your life savings?"},
    {"question": "Who would you want by your side in a life-or-death situation?"},
    {"question": "Who would you trust to raise your child if something happened to you?"},
    {"question": "Who would you rather be stranded with on a desert island?"},
    {"question": "Who would you trust more with your darkest secret?"},
    {"question": "Who would make a better superhero?"},
    {"question": "Who would you choose to switch lives with forever?"},
    {"question": "Who would you trust to make medical decisions for you?"},
    {"question": "Who would be more likely to sacrifice themselves to save others?"},
    {"question": "Who would handle fame better?"},
    {"question": "Who would you trust to lead a country through a crisis?"},
    {"question": "Who would win in a battle of wit and strategy?"},
    {"question": "Who would be more successful starting from zero in a foreign country?"},
    {"question": "Who would you want as your emergency contact?"},
    {"question": "Who would handle absolute power more responsibly?"},
    {"question": "Who has the most embarrassing Tinder profile?"},
    {"question": "Who is most likely to become a sugar daddy/mommy?"},
    {"question": "Who would survive longer in prison?"},
    {"question": "Who would make the worst decisions after winning the lottery?"},
    {"question": "Who could drink the most shots in 30 minutes and still walk straight?"},
    {"question": "Who would make better decisions after 5 drinks?"},
    {"question": "Who would you trust to be your designated driver?"},
    {"question": "Who has the most questionable search history?"},
    {"question": "Who would win in a drinking contest without getting sick?"},
    {"question": "Who is most likely to start an OnlyFans?"},
    {"question": "Who would make the worst roommate?"},
    {"question": "Who is most likely to end up on reality TV?"},
    {"question": "Who would get kicked out of a casino first?"},
    {"question": "Who has the better poker face?"},
    {"question": "Who takes a shot right now!"},
    {"question": "Who would make more money in their first year on TikTok?"},
    {"question": "Who is most likely to join a cult?"},
    {"question": "Who would survive longer in the wilderness without internet?"},
    {"question": "Who would make worse decisions during a midlife crisis?"},
    {"question": "Who is most likely to start a controversial tweet thread?"},
    {"question": "Who would make the best dictator?"},
    {"question": "Who would survive a night in a haunted house?"},
    {"question": "Who is most likely to get scammed by a Nigerian prince?"},
    {"question": "Who would make more money as an influencer?"},
    {"question": "Who would win in a rap battle?"},
    {"question": "Who would get canceled on social media first?"},
    {"question": "Who is most likely to become a conspiracy theorist?"},
    {"question": "Who would make worse financial decisions after a breakup?"},
    {"question": "Who would be more successful in Las Vegas?"},
    {"question": "Who would make a better cult leader?"},
    {"question": "Who is most likely to accidentally start a revolution?"},
    {"question": "Who would survive longer in a horror movie?"},
    {"question": "Who would make more money in their first month as a stripper?"},
    {"question": "Who would be worse at keeping a major secret?"},
    {"question": "Who would do better in an underground fight club?"},
    {"question": "Who is most likely to become famous for something embarrassing?"},
    {"question": "Who would make worse decisions during a quarter-life crisis?"},
    {"question": "Who would be more successful selling NFTs?"},
    {"question": "Who would make a better professional gambler?"},
    {"question": "Who would be more likely to accidentally join the wrong Zoom meeting naked?"},
    {"question": "Who would be worse at explaining their job to their grandparents?"},
    {"question": "Who would make more questionable decisions in Vegas?"},
    {"question": "Who would be more likely to become a meme?"}
]

spicy_en = [
    {"question": "Who flirts more?"},
    {"question": "Who is a better kisser?"},
    {"question": "Who is more into BDSM?"},
    {"question": "Who has the wildest fantasies?"},
    {"question": "Who would try group sex first?"},
    {"question": "Who is more likely to enjoy being tied up?"},
    {"question": "Who is does roleplaying in bed?"},
    {"question": "Who has had the riskiest one-night stand?"},
    {"question": "Who plays with toys?"},
    {"question": "Who is the loudest?"},
    {"question": "Who is most likely to have a hidden fetish?"},
    {"question": "Whose sexuality is more questionable?"},
    {"question": "Who masturbates every day?"},
    {"question": "Who will masturbate after they get home tonight?"},
    {"question": "Who has more sex?"},
    {"question": "Who is sexier?"},
    {"question": "Who has had sex with someone here?"},
    {"question": "Who will want to hook up with someone here?"},
    {"question": "Which one would you like to hook up with?"},
    {"question": "Who has dared to get intimate in a public place?"},
    {"question": "Who is more likely to have a threesome?"},
    {"question": "Who has the most adventurous sex life?"},
    {"question": "Who is more likely to send nudes?"},
    {"question": "Who has the most unusual turn-ons?"},
    {"question": "Who is more likely to have a secret affair?"},
    {"question": "Who is more likely to have a one-night stand?"},
    {"question": "Who is more likely to talk dirty?"},
    {"question": "Who is more likely to have a sex tape?"},
    {"question": "Who is more likely to have a friends-with-benefits relationship?"},
    {"question": "Who has power fetish?"},
    {"question": "Who is the sub?"},
    {"question": "Who is the dom?"},
    {"question": "Who is more likely to have a sexual encounter with a stranger?"},
    {"question": "Who prefers the same gender as themselves?"},
    {"question": "Who has a workplace affair?"}
]

questionsets = {
    'Easy': easy_en,
    'Medium': medium_en,
    'Hard': hard_en,
    'Spicy': spicy_en,
    'Controversial': controversial_en,
    'Controversial (fi)': controversial_fi
}